version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: contact-management-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: contact_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: contact-management-backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://admin:admin123@postgres:5432/contact_management
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: contact-management-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:
